CREATE TABLE IF NOT EXISTS posts (
	id BIGSERIAL PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	author VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	view_count BIGINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE posts ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS members (
	id BIGSERIAL PRIMARY KEY,
	login_id VARCHAR(50) NOT NULL UNIQUE,
	password_hash VARCHAR(100) NOT NULL,
	name VARCHAR(100) NOT NULL,
	phone VARCHAR(30) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS refresh_tokens (
	id BIGSERIAL PRIMARY KEY,
	member_id BIGINT NOT NULL REFERENCES members(id) ON DELETE CASCADE,
	token_hash VARCHAR(64) NOT NULL UNIQUE,
	expires_at TIMESTAMP NOT NULL,
	revoked BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	last_used_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS files (
	id BIGSERIAL PRIMARY KEY,
	post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
	comment_id BIGINT,
	original_name VARCHAR(255) NOT NULL,
	stored_name VARCHAR(255) NOT NULL,
	file_path VARCHAR(500) NOT NULL,
	content_type VARCHAR(100),
	file_size BIGINT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE files ALTER COLUMN post_id DROP NOT NULL;
ALTER TABLE files ADD COLUMN IF NOT EXISTS comment_id BIGINT;

CREATE TABLE IF NOT EXISTS comments (
	id BIGSERIAL PRIMARY KEY,
	post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	parent_id BIGINT REFERENCES comments(id),
	author VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	deleted BOOLEAN NOT NULL DEFAULT FALSE,
	edited BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP
);

ALTER TABLE files DROP CONSTRAINT IF EXISTS files_comment_id_fkey;
ALTER TABLE files ADD CONSTRAINT files_comment_id_fkey
	FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE;

CREATE TABLE IF NOT EXISTS post_views (
	id BIGSERIAL PRIMARY KEY,
	post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	viewer_key VARCHAR(200) NOT NULL,
	viewed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (post_id, viewer_key)
);
