CREATE TABLE IF NOT EXISTS posts (
	id BIGSERIAL PRIMARY KEY,
	title VARCHAR(200) NOT NULL,
	author VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	view_count BIGINT NOT NULL DEFAULT 0,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE posts ADD COLUMN IF NOT EXISTS view_count BIGINT NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS members (
	id BIGSERIAL PRIMARY KEY,
	login_id VARCHAR(50) NOT NULL UNIQUE,
	password_hash VARCHAR(100) NOT NULL,
	name VARCHAR(100) NOT NULL,
	phone VARCHAR(30) NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS files (
	id BIGSERIAL PRIMARY KEY,
	post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
	original_name VARCHAR(255) NOT NULL,
	stored_name VARCHAR(255) NOT NULL,
	file_path VARCHAR(500) NOT NULL,
	content_type VARCHAR(100),
	file_size BIGINT,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE files ALTER COLUMN post_id DROP NOT NULL;

CREATE TABLE IF NOT EXISTS comments (
	id BIGSERIAL PRIMARY KEY,
	post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	parent_id BIGINT REFERENCES comments(id),
	author VARCHAR(100) NOT NULL,
	content TEXT NOT NULL,
	deleted BOOLEAN NOT NULL DEFAULT FALSE,
	edited BOOLEAN NOT NULL DEFAULT FALSE,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS post_views (
	id BIGSERIAL PRIMARY KEY,
	post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
	viewer_key VARCHAR(200) NOT NULL,
	viewed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE (post_id, viewer_key)
);
